preferred_auth_method = "apikey"
approval_policy = "untrusted"
sandbox_mode    = "read-only"

[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENAI_API_KEY"
